# Generated by Django 5.2.1 on 2025-06-03 13:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_alter_commentslvl1_date_alter_commentslvl1_writer_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentslvl2',
            name='under_comment',
        ),
        migrations.RemoveField(
            model_name='commentslvl2',
            name='reply_to',
        ),
        migrations.RemoveField(
            model_name='commentslvl2',
            name='writer',
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=8000)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('reply_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.comments')),
                ('under_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.posts')),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='CommentsLvl1',
        ),
        migrations.DeleteModel(
            name='CommentsLvl2',
        ),
    ]
